### ISSUE TITLE
Requirements RFC

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-task-runner#3]
# nim-task-runner RFC
For both `nim-status` and `nim-status-client`, we are in need of a way to perform non-blocking I/O and compute tasks.

## Intro
![imgur](https://imgur.com/4Ug7EkH.png)
We would like the task runner library to be able to satisfy the needs of both of the above aforementioned libs and in the manner depicted in the figure above. As mentioned in https://github.com/status-im/nim-status-client/issues/527#issue-652609654 by @zah, here is a high-level idea of how this task runner lib would function, keeping in mind these specs are with `nim-status-client` in mind, hence the GUI requirement:
> A solution is to introduce an I/O thread that will run a separate message loop responsible for operations that may perform I/O and computational tasks without blocking the GUI thread. Then the workflow will be like this:
> 1) User performs action
> 2) Code running on the GUI threads decides to create a "task" for the I/O thread. The task is posted to something we call "AsyncChannel"
> 3) A loop in the I/O thread receives the task from the AsyncChannel. It starts executing arbitrary code using the async/await paradign. Multiple such tasks can progress in parallel (similar to goroutines). 
> 4) Some of the tasks in the I/O thread perform network requests to the Status GO RPC service. These requests are handled in the Status Go thread. The results are awaited and handled back in the Nim I/O thread.
> 5) Any such I/O or compute task can notify the UI for progress at any time by sending a Qt signal back to the UI thread.
> With this setup, you'll have 3 long-running threads and you don't need to deal with spawning new ones. The ownership of all the data is well assigned to a thread and there are no gc safety issues 

## Current `AsyncChannel[T]` work
The bulk of this lib will likely contain the work presented in https://github.com/status-im/nim-chronos/pull/45. 

### Thread pool of `AsyncChannel[T]`s or a single `AsyncChannel[T]`?
As described in the intro, there is meant to be one long-running thread that contains an `AsyncChannel[T]`. This will allow us to run asynchronous I/O and compute tasks in the long-running thread without blocking the originating thread. However, this assumes that the I/O and compute tasks utilise asynchronous APIs to perform their work. We are concerned that a lot of the tasks we currently perform are not asynchronous, and would need to be modified to work asynchronously. We are concerned that if the existing tasks are not converted, they will run synchronously, and the asynchronous nature of the `AsyncChannel[T]` will be more or less forfeited and each task would block other tasks from being run (IOW they'd be run serially). 

#### Thread pool option
One option we discussed was to create a thread pool that creates a new thread for each task to be run. Each thread would create an `AsyncChannel[T]` and the task would be run via the `AsyncChannel[T]`. The thread pool would have limitations as to the number of allowed threads and would require some management of the pool. In the case of `nim-status`, where most of the tasks would be database CRUD, multiple threads shouldn't be an issue as long as each thread only has one DB connection and each execution against the DB is run inside of a transaction.

This option seems very similar to the "multi-threading async" test from the `AsyncChannel[T]` tests:
```nim
    proc testMtAsync(threads: int, runs: int, queue: int): bool =
      var tun = newAsyncChannel[int](queue)
      var arg = ThreadArg(tun: tun, runs: runs)
      var thrs = newSeq[Thread[ThreadArg]](threads)
      for i in 0..<threads:
        createThread(thrs[i], threadSyncFunc2, arg)
      var total = threads * runs
      waitFor asyncReceiver(arg, total)
      joinThreads(thrs)
      result = true
```
Of course this doesn't include any thread pool management, but the concept is the same.

## Writing procs to be run in the task runner
Developers hoping to use the task runner will need to be sure that each proc to ultimately be executed by the task meets the following requirements:
1. Must be passed by pointer (likely can be abstracted out in the same template as #4 below).
1. Must be pure in the sense that it does not modify memory outside of its own scope (must have `{.noSideEffect.}`).
2. Data used by the proc must not be from a mutable source (cannot be altered by other threads).
2. Params passed to the proc must be copied in memory. In other words, parameters must be passed by value instead of by reference (this can likely be abstracted in a template).

**Comment by zah** [comment]
An `AsyncChannel[T]` is a communication link between two threads that delivers exactly one type of message (although it's legal for the message to be a case object or a polymorphic base type). Thus, each channel usually has a very specific purpose within the application and a message type specifically crafted for this purpose.

The single I/O thread can support a large number of concurrently running channels without problems. The receiving end of each channel will be a `while` loop that waits for the next message with `await`. When a new message arrives on any of the channels, Chronos will take care of awaking the right while loop.

If your tasks are synchronous in the sense that they use blocking I/O while performing their computations, then this may indeed block the progress of the I/O thread while the CPU stays idle and this would spell troubles for you. In that case, you would also involve a [thread pool](https://github.com/yglukhov/threadpools) in the setup. Once a thread in the thread pool completes its work, it can also use an `AsyncChannel` to post its results back to the I/O thread. Having that said, I would strongly recommend avoiding any blocking I/O. You would then worry only about long-running CPU intensive tasks that may introduce unfair delays in the processing of other tasks, but this should be a problem only if you are close to saturating a single core on the machine and you need to use additional cores. I think It would be unreasonable for a messenger to induce such loads on the user's machine, so the solution in such a hypothetical scenario would be to optimize the specific CPU intensive task.

> Must be passed by pointer (likely can be abstracted out in the same template as #4 below).

The heap structures used by Nim's garbage collector are not thread-safe. This means that each thread has its own heap and you cannot pass garbage collected objects by pointer between threads. Doing this may result in the type of crashes you were debugging recently. There are two safe ways to pass objects between threads:

1) Serialize them to bytes and then recreate them on the other side of the channel
2) Use manually-managed memory with `malloc` and `free` (you'll be exposed to the risk of introducing memory leaks)

I think your goal should be to realize option 1) with my help by pairing nim-serialization with the low-level async channel code.

**Comment by arnetheduck** [comment]
> Serialize them to bytes and then recreate them on the other side of the channel

this is completely unsafe for so many reasons that I'm surprised it's even suggested - memory reference stability, resource ownership, really the basic semantics of `ref` in the first place (specially tricky with hard-to-spot `ref object`) etc - the reasonable thing to do here is that `T` should be constrained to types that `supportsCopyMem` - ie trivial types in c++ parlance that contain only data and have no meta functions like destructors etc attached to them.

Allowing any kind of ref to travel across thread barriers, serialized or not, leads to edge cases and hard-to-debug bugs - programs that think they need this are likely poorly designed to begin with as this breaks the most basic assumptions about the semantics of `ref`, leading to completely unexpected behaviour that cannot be reasoned about.

**Comment by zah** [comment]
Er, why do you focus on `ref` in your remarks? The user of the `AsyncChannel[T]` selects the message type as a generic parameter. It would be indeed unusual to select a ref type there, but going as far as forbidding it at the level of the library sounds like a bit extreme position on the guiding vs enabling spectrum.

When I said "pass objects between threads", I was referring to any kind of value object that makes sense for the application in the classic shared-nothing message passing model. Requiring such objects to be `supportsCopyMem` types would be a bit silly because it would rule out basic types such as `string` or `seq[byte]`.

**Comment by cheatfate** [comment]
I really think that 100% of your usecases could be satisfied by "Unix domain socket" or OS "pipe". Both primitives supported by `nim-chronos` and i think by some QML library.
If you need to make it more responsive you could use `request->response` scheme with polling socket/pipe, it will look like this:

1. UI threads sends request over socket/pipe to IO thread.
2. I/O threads consumes request and sends ack/confirmation back to UI thread.
3. I/O thread starts processing request
4. UI thread could check data available in `socket/pipe` in some `idle` handler or timer handler (polling socket/pipe).
5. As soon as data available UI thread perform reading of response and trigger some QML event.

**Comment by richard-ramos** [comment]
Something to take in account for the design of the task runner:
1. QT takes ownership of the main thread. 
2. To be able to notify the UI from the task runner, we need a way to trigger the QObject [slots/signals](https://doc.qt.io/qt-5/signalsandslots.html). In desktop the QObjects are ref objects like this:

```nim
QtObject:
  type MyObject* = ref object of QAbstractListModel
  proc setup(self: MyObject) = self.QAbstractListModel.setup
  proc delete(self: MyObject) = 
    self.QAbstractListModel.delete
  proc newMyObject*(): MyObject =
    new(result, delete)
    result.setup()
  proc someSIgnal*(self: MyObject) {.signal.}
  proc someSlot*(self: MyObject): QVariant {.slot.}  =
    # TODO
```

So far, the only ways we've found to trigger a slot in a QObject from a separate thread is 

1. Thru QT's `invokeMethod` which we exposed thru this proc in nimqml/dotherside

```cpp
void dos_signal(::DosQObject *vptr, const char *signal, const char *slot) //
{
    auto qobject = static_cast<QObject *>(vptr);
    std::string copy = signal; // signal comes from nim, and might be GC. Creating a copy (QT will handle the freeing)
    QMetaObject::invokeMethod(qobject, slot, Qt::QueuedConnection, Q_ARG(QString, copy.c_str()));
}
```
```nim
proc dos_signal(vptr: pointer, signal: cstring, slot: cstring) {.cdecl, dynlib: dynLibName, importc.}

proc signal_handler*(receiver: pointer, signal: cstring, slot: cstring) =
  var dosqobj = cast[DosQObject](receiver)
  if(dosqobj.isNil == false):
    dos_signal(receiver, signal, slot)
```

To use these functions: 
```nim
let myObjectPtr = cast[pointer](myObject.vptr)
signal_handler(myObjectPtr, "The data", "someSlot")
```

2. Invoking the ref object slot from a separate thread, but in this case we need the qObject to reside in some global variable, and add locks. I've had mixed results with this method, hence why Desktop uses the first approach

**Comment by cheatfate** [comment]
Could somebody explain why you need many threads?

**Comment by emizzle** [comment]
> Could somebody explain why you need many threads?

For `nim-status-client` (desktop), the purpose is to prevent blocking of the UI thread.
For `nim-status` (status-go in nim), I believe the purpose is to handle tasks provided from multiple sources (`nim-waku`, `status-go`, `nim-status` consumers) in a queue-like fashion.

**Comment by arnetheduck** [comment]
> Er, why do you focus on ref in your remarks?

because of the incredible amount of bugs that I have had to fix when `ref` types are involved, in async code in general - this will get an order of magnitude worse the moment we have queues and channels that have unintuitive ref behaviour coupled with threads _and_ async.

> going as far as forbidding

the user that wants to marshal `ref` types still has the option to do so: they can call their favourite serialization library _explicitly_ when they want to play with this - just like you have to call `deepCopy` explicitly - it would be very unintuitive if `ref` types resulted in a _different_ instance on the other side of the queue - this is simply not expected behaviour for ref types - in addition, it pulls in a completely unnecessary dependency on `nim-serialization` which turns a simple channel into an incredible maze of generic code.

> Requiring such objects to be supportsCopyMem types would be a bit silly because it would rule out basic types such as string or seq[byte].

good point - seq and string are indeed value types so it makes sense to support them - this would still conform to expectations, though it does complicate the implementation.

**Comment by zah** [comment]
I think there is some confusion here. The implementation plan I've proposed is based on multiple layers of APIs. At the lowest level, you have the channel currently sitting in Chronos that can transfer bytes. The nim-serialization based channels are wrapping this lower-level API to produce a type-safe version that transfers objects with convenient syntax.

**Comment by cheatfate** [comment]
> 
> 
> > Could somebody explain why you need many threads?
> 
> For `nim-status-client` (desktop), the purpose is to prevent blocking of the UI thread.
> For `nim-status` (status-go in nim), I believe the purpose is to handle tasks provided from multiple sources (`nim-waku`, `status-go`, `nim-status` consumers) in a queue-like fashion.

If i remember it right `nim-waku` is chronos-based asynchronous implementation of protocol (without threads involved), `nim-status` should be also single threaded. The biggest problem here is `status-go` which is very complex to connect with any other language (because of go scheduler which uses many threads).

First of all to combine all this things you ***DON'T NEED***:
1. `AsyncChannel[T]`, `Channel[T]` or any other Event from Nim's stdlib and friends.
2. You don't need `nim-serialization` and friends.

The only thing you need is ability to create and use local sockets. So why sockets? Because UI thread is implemented using QML, and QML could integrate cross-platform socket notification routine into Qt's event loop https://doc.qt.io/qt-5/qsocketnotifier.html. So what the plan:
1. You can use `nim-status` and `nim-waku` in one thread or if you need you can start `nim-status` in one thread and `nim-waku` in another.
2. Thread with `nim-status` and/or `nim-waku` bind to local address/port and starts simple TCP server where it listening for requests, process this requests and send responses back.
3. When somebody pressed button in UI, UI thread establish connection with appropriate local address/port and sends specific request to the `nim-status` and/or `nim-waku`. After that it registers this socket connection using QSocketNotifier class with callback which will be scheduled when data will be available. When callback got invoked it will read the data from the socket and shows information in UI.

**Comment by arnetheduck** [comment]
> Because UI thread is implemented using QML, 

This is a good point - for using QT and a UI thread, it is indeed easier to use a socket to integrate the two threads / event loops - this way each stays fully within its own world - otherwise, one has to implement a notification service that wakes the "other" loop and plucks things off the channel - this is a good lowest-common-denominator approach.


In this world, `AsyncChannel`  be useful in applications that run _two or more_ chronos loops for some reason - or it would need to have pluggable notification infrastructure so it can be integrated in "other" event loops - or we need a `QtAsyncChannel` that binds qt and chronos specifically - from a functional point of view, there would be no difference to a socket except some minor efficiency gain (that can easily be done later iff needed)

**Comment by zah** [comment]
With sockets and pipes, one also has to worry about protecting the exposed end-point from other applications on the same computer, including the web browser if the approach is [naive enough](https://www.exploit-db.com/exploits/39218). Running multiple instances of the same application also becomes more complicated.

I don't understand why there is such a strong resistance against doing the right thing here. After all, most of the code is already written and pretty much all event loop libraries have similar support for sending custom messages across threads without relying on exposed end-points:

https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/post.html
http://docs.libuv.org/en/v1.x/async.html

I've had some long conversations with the desktop team and it's pretty clear to me what they need. You still focus on details that are very far removed from the high-level APIs they would like to have.

**Comment by arnetheduck** [comment]
Yes, but the point here is that the loops are rarely _interoperable_ - ie you can't block and consume an asyncchannel from the ui thread easily

**Comment by arnetheduck** [comment]
so there are a couple of things here:

* how much magic should the framework do? aka how little should the library user have a chance of understanding when something goes wrong or against expectations? the mental model around value types maps well to what de facto happens on a channel - this can be magic - `ref` however does not - it's wrong to make this magic because it leads to dissonance between model and reality, and the dissonance leads to bugs - shipping pointers and refs across threads _rightfully_ should be difficult and explicit
 
* the technical challenge of interoperability between different loop frameworks - there's no one _true_ channel multiplexer in this design, like `go` - instead, one can either write lots of adapters for different event loop frameworks or use something all frameworks support natively - sockets are one such mechanism, pipes another. of course, if the question was how to do MPSC between chronos-controlled threads, it would be simple because the chronos event loop could be woken up easily - as it stands however, one would have to post on the queue, then post on the UI queue to wake that loop up and poll the chronos queue

**Comment by zah** [comment]
Please read the original description in the issue:

> Any such I/O or compute task can notify the UI for progress at any time by sending a Qt signal back to the UI thread.

The UI thread won't consume async channels. It would be notified with Qt signals which happens to be the mechanism already used for this purpose by the numerous background threads spawned in the current code.

And again, nobody plans to transport `ref` types across the channels.

**Comment by michaelsbradleyjr** [comment]
@richard-ramos, @emizzle, and I are very grateful for the ongoing discussion.

I don't want to derail it, but there was a [blog post](https://nim-lang.org/blog/2020/12/08/introducing-orc.html) earlier today re: Nim's ORC gc, and I ended up looking at a forum discussion re: the same from a few months ago: *[New garbage collector --gc:orc is a joy to use](https://forum.nim-lang.org/t/6483)*.

The person who started that discussion used ORC in relation to building a [work queue](https://gist.github.com/treeform/3e8c3be53b2999d709dadc2bc2b4e097) and he describes some advantages.

That all sounds very appealing, but I don't know how to judge whether Nim v1.4 and ORC are out of reach for us, and if so for what reasons. Thanks for your input!

**Comment by cheatfate** [comment]
@zah resistance is because of complexity, its very easy to protect endpoints for sockets you just need to call `accept` once and never call it again, and now you will be 100% protected.

**Comment by michaelsbradleyjr** [comment]
Quick update: based on feedback from @arnetheduck in discord chat re: Nim v1.4 and ORC, we won't be exploring that route, not before Nim has gone through another release cycle at least.

After carefully considering everything discussed in previous comments, we've decided to attempt an implementation per @zah's recommendations. If we experience too many challenges during the implementation or it proves buggy, we'll use sockets/pipes instead.

The carved off async channel code will appear in this repo soon.

Thanks everybody!

**Comment by michaelsbradleyjr** [comment]
We're nearing critical mass on this repo becoming a proper library. See: https://github.com/status-im/nim-task-runner/pull/7#issuecomment-859108562.
